const mockProfiles = [
  {
    id: 1,
    name: "Sumit Krishnan",
    title: "DGCA-Certified RPAS Instructor",
    location: "Hyderabad, India",
    experience: "11+ years",
    rating: 4.8,
    projects: 120,
    tags: ["Drone Pilot Training", "Flight Mechanics"],
    image: "https://xsgames.co/randomusers/assets/avatars/male/24.jpg",
    about: [
      "DGCA RPAS Instructor & Aerospace Educator",
      "National Award-Winning UAV Specialist",
      "12+ Years Training Pilots across India",
      "Keynote @ STEM Summits",
      "Mentor to 1000+ students & professionals",
    ],
    highlights: ["DGCA Certified", "12+ Yrs Experience", "Award Winner"],
    skills: [
      {
        title: "Drone Training",
        icon: "star",
        details: ["RPAS Curriculum", "DGCA Compliance"],
        level: 90,
      },
      {
        title: "Flight Dynamics",
        icon: "school",
        details: ["Aerodynamics", "Payload Handling"],
        level: 85,
      },
      {
        title: "Mentorship",
        icon: "verified",
        details: ["Pilot Coaching", "Career Guidance"],
        level: 92,
      },
    ],
    services: [
      {
        title: "Drone Training",
        details: ["RPAS Certification", "Flight Practice"],
      },
      {
        title: "Aviation Consulting",
        details: ["DGCA Documentation", "Flight Ops Audit"],
      },
      {
        title: "Aerospace Education",
        details: ["STEM Curriculum", "UAV Seminars"],
      },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "sumit.krishnan@example.com",
    phone: "+91-9999999999",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Dev R",
    title: "CEO, UAV Systems Integrator",
    location: "Singapore",
    experience: "17+ years",
    rating: 5.0,
    projects: 85,
    tags: ["UAV Services", "System Integration"],
    image: "https://xsgames.co/randomusers/assets/avatars/male/23.jpg",
    about: [
      "Founder and CEO of DroneSys",
      "Leading UAV innovation globally",
      "Expert in technical system integration",
    ],
    highlights: ["Tech Leader", "17+ Years", "Global Reach"],
    skills: [
      {
        title: "Leadership",
        icon: "verified",
        details: ["Team Management", "Project Scaling"],
        level: 94,
      },
      {
        title: "System Design",
        icon: "school",
        details: ["Embedded UAV Systems", "Autonomous Navigation"],
        level: 88,
      },
      {
        title: "Project Strategy",
        icon: "star",
        details: ["Agile Practices", "Client Delivery"],
        level: 91,
      },
    ],
    services: [
      { title: "System Integration", details: ["Drone Hardware + Software"] },
      { title: "Consulting", details: ["Startups & Enterprises"] },
      { title: "Product Development", details: ["Full Stack UAV Solutions"] },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "dev.r@example.com",
    phone: "+65-12345678",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 3,
    name: "Amanda Davis",
    title: "Environmental Data Analyst",
    location: "Denver, CO",
    experience: "6 years",
    rating: 4.6,
    projects: 95,
    tags: ["Survey Analysis", "UAV Mapping"],
    image: "https://xsgames.co/randomusers/assets/avatars/female/22.jpg",
    about: [
      "Environmental data specialist",
      "Expert in UAV-assisted GIS",
      "Visual storyteller using spatial data",
    ],
    highlights: ["GIS Certified", "6 Years", "Data Analyst"],
    skills: [
      {
        title: "Data Analysis",
        icon: "school",
        details: ["UAV Data Cleanup", "GeoJSON Mapping"],
        level: 82,
      },
      {
        title: "GIS Mapping",
        icon: "star",
        details: ["ArcGIS Pro", "QGIS"],
        level: 88,
      },
      {
        title: "Visualization",
        icon: "verified",
        details: ["Heatmaps", "Geospatial Charts"],
        level: 80,
      },
    ],
    services: [
      { title: "Survey Analysis", details: ["Raw to Processed Reports"] },
      { title: "GIS Visualizations", details: ["Map Design", "3D Elevation"] },
    ],
    gallery: [
      "https://picsum.photos/200/300?random=1",
      "https://picsum.photos/200/300?random=2",
      "https://picsum.photos/200/300?random=3",
      "https://picsum.photos/200/300?random=4",
      "https://picsum.photos/200/300?random=5",
      
    ],

    email: "amanda.davis@example.com",
    phone: "+1-303-9876543",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "David Thompson",
    title: "Drone Pilot & 3D Mapper",
    location: "New York, USA",
    experience: "9 years",
    rating: 4.7,
    projects: 140,
    tags: ["Aerial Surveys", "3D Mapping"],
    image: "https://xsgames.co/randomusers/assets/avatars/male/21.jpg",
    about: [
      "Certified Drone Pilot with specialization in 3D mapping",
      "Served 30+ real estate firms in NYC",
      "Trained in photogrammetry and lidar scanning",
    ],
    highlights: ["FAA Licensed", "3D Expert", "Real Estate Pro"],
    skills: [
      {
        title: "3D Mapping",
        icon: "star",
        details: ["Pix4D", "DroneDeploy"],
        level: 85,
      },
      {
        title: "Flight Planning",
        icon: "school",
        details: ["Autonomous Routes", "Obstacle Avoidance"],
        level: 80,
      },
      {
        title: "Client Handling",
        icon: "verified",
        details: ["Requirement Gathering", "Post Delivery Support"],
        level: 75,
      },
    ],
    services: [
      { title: "3D Mapping", details: ["Real Estate", "Construction Sites"] },
      {
        title: "Custom Flights",
        details: ["Aerial Inspection", "Video Capture"],
      },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "david.t@example.com",
    phone: "+1-212-555-7890",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 5,
    name: "Emma Foster",
    title: "Drone Flight Instructor",
    location: "San Diego, CA",
    experience: "4 years",
    rating: 4.9,
    projects: 80,
    tags: ["Flight Safety", "UAV Training"],
    image: "https://xsgames.co/randomusers/assets/avatars/female/27.jpg",
    about: [
      "Passionate instructor certified by the FAA",
      "Trained 200+ beginner drone pilots",
      "Focus on safety and compliance with airspace regulations",
    ],
    highlights: ["FAA Certified", "Hands-on Trainer", "Beginner-Friendly"],
    skills: [
      {
        title: "Flight Instruction",
        icon: "school",
        details: ["Simulators", "Hands-on Flight"],
        level: 90,
      },
      {
        title: "Compliance",
        icon: "star",
        details: ["FAA Rules", "Airspace Zones"],
        level: 85,
      },
      {
        title: "Safety Protocols",
        icon: "verified",
        details: ["Emergency Handling", "Checklists"],
        level: 88,
      },
    ],
    services: [
      { title: "Basic Training", details: ["Simulated & Real Flights"] },
      {
        title: "Flight Safety",
        details: ["Risk Mitigation", "Best Practices"],
      },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],

    email: "emma.foster@example.com",
    phone: "+1-619-9876543",
    template: "TemplateOne",
  },
  {
    id: 6,
    name: "Kevin Brown",
    title: "UAV Software Developer",
    location: "Austin, TX",
    experience: "7 years",
    rating: 4.6,
    projects: 110,
    tags: ["Telemetry Systems", "Drone APIs"],
    image: "https://xsgames.co/randomusers/assets/avatars/male/26.jpg",
    about: [
      "Backend engineer for UAV communication stacks",
      "Built scalable APIs for drone telemetry",
      "Passionate about open-source drone control systems",
    ],
    highlights: ["Node.js Expert", "Telemetry Architect", "7+ Yrs Exp"],
    skills: [
      {
        title: "API Development",
        icon: "star",
        details: ["REST & WebSocket", "Drone Data Exchange"],
        level: 88,
      },
      {
        title: "System Architecture",
        icon: "school",
        details: ["Distributed Systems", "Microservices"],
        level: 85,
      },
      {
        title: "Security",
        icon: "verified",
        details: ["Auth Tokens", "Role-based Access"],
        level: 80,
      },
    ],
    services: [
      { title: "Telemetry Platform", details: ["Drone ↔ Dashboard Comm"] },
      { title: "System Security", details: ["OAuth", "JWT", "Rate Limits"] },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "kevin.b@example.com",
    phone: "+1-737-333-1234",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 7,
    name: "Lisa Wang",
    title: "AI/ML Drone Specialist",
    location: "San Francisco, CA",
    experience: "6+ years",
    rating: 4.9,
    projects: 95,
    tags: ["Autonomous Navigation", "Vision Systems"],
    image: "https://xsgames.co/randomusers/assets/avatars/female/28.jpg",
    about: [
      "Building AI systems for obstacle avoidance",
      "Pioneering computer vision for drones",
      "Worked on autonomous search & rescue drones",
    ],
    highlights: ["ML Certified", "ROS Dev", "6+ Yrs AI Exp"],
    skills: [
      {
        title: "Computer Vision",
        icon: "star",
        details: ["Object Detection", "SLAM"],
        level: 91,
      },
      {
        title: "AI & ML",
        icon: "school",
        details: ["TensorFlow", "OpenCV"],
        level: 89,
      },
      {
        title: "ROS Integration",
        icon: "verified",
        details: ["Sensor Fusion", "Path Planning"],
        level: 85,
      },
    ],
    services: [
      { title: "Vision Systems", details: ["Obstacle Detection"] },
      { title: "Autonomous Navigation", details: ["ML Route Optimization"] },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "lisa.w@example.com",
    phone: "+1-415-111-5678",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 8,
    name: "Robert Kim",
    title: "Aerial Cinematographer",
    location: "Los Angeles, CA",
    experience: "10+ years",
    rating: 4.7,
    projects: 150,
    tags: ["Cinematography", "Post-production"],
    image: "https://xsgames.co/randomusers/assets/avatars/male/27.jpg",
    about: [
      "Award-winning cinematographer for film & real estate",
      "Skilled in high-end FPV drone work",
      "Collaborated with Netflix and Amazon productions",
    ],
    highlights: ["Drone Filmmaker", "Netflix Pro", "10+ Yrs Experience"],
    skills: [
      {
        title: "Cinematography",
        icon: "star",
        details: ["FPV", "4K Shoots"],
        level: 95,
      },
      {
        title: "Post Production",
        icon: "school",
        details: ["DaVinci Resolve", "Adobe Premiere"],
        level: 85,
      },
      {
        title: "Creative Direction",
        icon: "verified",
        details: ["Storyboarding", "Scripting"],
        level: 80,
      },
    ],
    services: [
      { title: "Film Shoots", details: ["Aerial Scenes", "FPV Shots"] },
      { title: "Editing", details: ["Post-processing", "VFX"] },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "robert.k@example.com",
    phone: "+1-310-222-8888",
    template: "TemplateOne",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 9,
    name: "Maria Gonzalez",
    title: "GIS & Remote Sensing Specialist",
    location: "Austin, TX",
    experience: "5+ years",
    rating: 4.5,
    projects: 90,
    tags: ["Agricultural Mapping", "Remote Sensing"],
    image: "https://xsgames.co/randomusers/assets/avatars/female/25.jpg",
    about: [
      "Expert in GIS-based crop health analysis",
      "Skilled in multispectral image processing",
      "Worked with agri-tech startups globally",
    ],
    highlights: ["GIS Pro", "AgriTech Innovator", "NDVI Expert"],
    skills: [
      {
        title: "Remote Sensing",
        icon: "star",
        details: ["NDVI", "Thermal Imagery"],
        level: 88,
      },
      {
        title: "GIS Analytics",
        icon: "school",
        details: ["QGIS", "ArcGIS"],
        level: 84,
      },
      {
        title: "Data Reporting",
        icon: "verified",
        details: ["Excel Dashboards", "Insights"],
        level: 79,
      },
    ],
    services: [
      { title: "Agri Drone Mapping", details: ["Crop Health Reports"] },
      { title: "GIS Dashboards", details: ["Farm Data Integration"] },
    ],
    gallery: [
      "https://source.unsplash.com/400x300/?drone&sig=1",
      "https://source.unsplash.com/400x300/?aerospace&sig=2",
    ],
    email: "maria.g@example.com",
    phone: "+1-737-555-1234",
    template: "TemplateTwo",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
  {
    id: 10,
    name: "Sanjay Patel",
    title: "Drone Racing Champion",
    location: "Mumbai, India",
    experience: "5 years",
    rating: 4.8,
    projects: 70,
    tags: ["FPV Racing", "Drone Builds"],
    image: "https://xsgames.co/randomusers/assets/avatars/male/20.jpg",
    about: [
      "India’s fastest FPV drone racer (2023)",
      "Expert in custom drone builds",
      "Conducts racing bootcamps for students",
    ],
    highlights: ["Race Champ", "Build Expert", "FPV Pro"],
    skills: [
      {
        title: "FPV Racing",
        icon: "star",
        details: ["Speed Tuning", "High-G Maneuvers"],
        level: 93,
      },
      {
        title: "Custom Builds",
        icon: "school",
        details: ["Soldering", "ESC Programming"],
        level: 87,
      },
      {
        title: "Training",
        icon: "verified",
        details: ["Bootcamps", "Workshops"],
        level: 89,
      },
    ],
    services: [
      { title: "Race Training", details: ["Pro-Level FPV Bootcamp"] },
      { title: "Drone Builds", details: ["Custom Tuning & Assembly"] },
    ],
    gallery: [
      "https://picsum.photos/400/300?random=1",
      "https://picsum.photos/400/300?random=2",
    ],
    email: "sanjay.p@example.com",
    phone: "+91-7777777777",
    template: "TemplateTwo",
    testimonials: [
      {
        name: "Rohit Sharma",
        role: "Product Manager",
        quote: "Absolutely loved working with this team — fast and efficient!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/male/5.jpg",
      },
      {
        name: "Sneha Kapoor",
        role: "CEO, Creatix",
        quote: "Impressive design work, I highly recommend their services!",
        avatar: "https://xsgames.co/randomusers/assets/avatars/female/11.jpg",
      },
    ],
  },
];

export default mockProfiles;
